version: '3.8'
services:
  api-gateway:
    build:
      context: ./ApiGateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - book-service
    networks:
      - microservices-network

  user-service:
    build:
      context: ./UserService
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - microservices-network

  book-service:
    build:
      context: ./BookService
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - microservices-network

networks:
  microservices-network:
